/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up/$'
import { Route as SignInSsoCallbackRouteImport } from './routes/sign-in/sso-callback'
import { Route as SignInSplatRouteImport } from './routes/sign-in/$'
import { Route as DashboardEquipmentsRouteImport } from './routes/dashboard/equipments'
import { Route as DashboardRentalsIndexRouteImport } from './routes/dashboard/rentals/index'
import { Route as DashboardCustomersIndexRouteImport } from './routes/dashboard/customers/index'
import { Route as DashboardRentalsIdRouteImport } from './routes/dashboard/rentals/$id'
import { Route as DashboardEquipmentIdRouteImport } from './routes/dashboard/equipment/$id'
import { Route as DashboardCustomersIdRouteImport } from './routes/dashboard/customers/$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSsoCallbackRoute = SignInSsoCallbackRouteImport.update({
  id: '/sign-in/sso-callback',
  path: '/sign-in/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEquipmentsRoute = DashboardEquipmentsRouteImport.update({
  id: '/equipments',
  path: '/equipments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRentalsIndexRoute = DashboardRentalsIndexRouteImport.update({
  id: '/rentals/',
  path: '/rentals/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersIndexRoute = DashboardCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRentalsIdRoute = DashboardRentalsIdRouteImport.update({
  id: '/rentals/$id',
  path: '/rentals/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEquipmentIdRoute = DashboardEquipmentIdRouteImport.update({
  id: '/equipment/$id',
  path: '/equipment/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersIdRoute = DashboardCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/equipments': typeof DashboardEquipmentsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/dashboard/customers/$id': typeof DashboardCustomersIdRoute
  '/dashboard/equipment/$id': typeof DashboardEquipmentIdRoute
  '/dashboard/rentals/$id': typeof DashboardRentalsIdRoute
  '/dashboard/customers/': typeof DashboardCustomersIndexRoute
  '/dashboard/rentals/': typeof DashboardRentalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/equipments': typeof DashboardEquipmentsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard': typeof DashboardIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/dashboard/customers/$id': typeof DashboardCustomersIdRoute
  '/dashboard/equipment/$id': typeof DashboardEquipmentIdRoute
  '/dashboard/rentals/$id': typeof DashboardRentalsIdRoute
  '/dashboard/customers': typeof DashboardCustomersIndexRoute
  '/dashboard/rentals': typeof DashboardRentalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/equipments': typeof DashboardEquipmentsRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-in/sso-callback': typeof SignInSsoCallbackRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/dashboard/customers/$id': typeof DashboardCustomersIdRoute
  '/dashboard/equipment/$id': typeof DashboardEquipmentIdRoute
  '/dashboard/rentals/$id': typeof DashboardRentalsIdRoute
  '/dashboard/customers/': typeof DashboardCustomersIndexRoute
  '/dashboard/rentals/': typeof DashboardRentalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/equipments'
    | '/sign-in/$'
    | '/sign-in/sso-callback'
    | '/sign-up/$'
    | '/dashboard/'
    | '/sign-in/'
    | '/sign-up/'
    | '/dashboard/customers/$id'
    | '/dashboard/equipment/$id'
    | '/dashboard/rentals/$id'
    | '/dashboard/customers/'
    | '/dashboard/rentals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/equipments'
    | '/sign-in/$'
    | '/sign-in/sso-callback'
    | '/sign-up/$'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/customers/$id'
    | '/dashboard/equipment/$id'
    | '/dashboard/rentals/$id'
    | '/dashboard/customers'
    | '/dashboard/rentals'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/equipments'
    | '/sign-in/$'
    | '/sign-in/sso-callback'
    | '/sign-up/$'
    | '/dashboard/'
    | '/sign-in/'
    | '/sign-up/'
    | '/dashboard/customers/$id'
    | '/dashboard/equipment/$id'
    | '/dashboard/rentals/$id'
    | '/dashboard/customers/'
    | '/dashboard/rentals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  SignInSsoCallbackRoute: typeof SignInSsoCallbackRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  SignInIndexRoute: typeof SignInIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/sso-callback': {
      id: '/sign-in/sso-callback'
      path: '/sign-in/sso-callback'
      fullPath: '/sign-in/sso-callback'
      preLoaderRoute: typeof SignInSsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/equipments': {
      id: '/dashboard/equipments'
      path: '/equipments'
      fullPath: '/dashboard/equipments'
      preLoaderRoute: typeof DashboardEquipmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rentals/': {
      id: '/dashboard/rentals/'
      path: '/rentals'
      fullPath: '/dashboard/rentals/'
      preLoaderRoute: typeof DashboardRentalsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers/': {
      id: '/dashboard/customers/'
      path: '/customers'
      fullPath: '/dashboard/customers/'
      preLoaderRoute: typeof DashboardCustomersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rentals/$id': {
      id: '/dashboard/rentals/$id'
      path: '/rentals/$id'
      fullPath: '/dashboard/rentals/$id'
      preLoaderRoute: typeof DashboardRentalsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/equipment/$id': {
      id: '/dashboard/equipment/$id'
      path: '/equipment/$id'
      fullPath: '/dashboard/equipment/$id'
      preLoaderRoute: typeof DashboardEquipmentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers/$id': {
      id: '/dashboard/customers/$id'
      path: '/customers/$id'
      fullPath: '/dashboard/customers/$id'
      preLoaderRoute: typeof DashboardCustomersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardEquipmentsRoute: typeof DashboardEquipmentsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCustomersIdRoute: typeof DashboardCustomersIdRoute
  DashboardEquipmentIdRoute: typeof DashboardEquipmentIdRoute
  DashboardRentalsIdRoute: typeof DashboardRentalsIdRoute
  DashboardCustomersIndexRoute: typeof DashboardCustomersIndexRoute
  DashboardRentalsIndexRoute: typeof DashboardRentalsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEquipmentsRoute: DashboardEquipmentsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCustomersIdRoute: DashboardCustomersIdRoute,
  DashboardEquipmentIdRoute: DashboardEquipmentIdRoute,
  DashboardRentalsIdRoute: DashboardRentalsIdRoute,
  DashboardCustomersIndexRoute: DashboardCustomersIndexRoute,
  DashboardRentalsIndexRoute: DashboardRentalsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  SignInSsoCallbackRoute: SignInSsoCallbackRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  SignInIndexRoute: SignInIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
